### ISSUE TITLE
Frameworks mention "Bristol Circuit Format"--what is this?

### ISSUE THREAD

**Issue by danxinnoble** [rdragos/awesome-mpc#13]
Hello Dragos

I have been looking at some of the frameworks you mention and am very confused by something. A number mention or have links to a "Bristol Circuit format."
- batchDualEx has a Readme.md saying that circuits "Must be in this format", linking to https://www.cs.bris.ac.uk/Research/CryptographySecurity/MPC/. But this link is broken.
- TinyLEGO has the same link in its Readme. 
- DUPLO's latest commit (https://github.com/AarhusCrypto/DUPLO/commit/0d14ad0a225d8f2355549d64eac6330ceba1f47c) has the commit message "Added option to use “bristol” circuits as commandline input to mains".

I am also somewhat confused by these statements as the main work in MPC that I am aware of at Bristol is the SPDZ/SCALE-MAMBA project. Which as far as I understand is not based on Boolean circuits.

Since you are a PhD student at Bristol, I was wondering if you knew whether, at a certain point in time, there was a somewhat standardized circuit format that was used by Bristol's crypto team and others? Is there still a description of this circuit format, and is it still being used widely?

Best
Daniel

**Comment by rdragos** [comment]
Hi Daniel,

To be honest I've never used the so-called Bristol format as I had started
my PhD when Bristol people stopped using them.

What I know is that there is a tool which converts programs into Bristol
format: check it here -
https://www.seceng.informatik.tu-darmstadt.de/research/software/cbmc-gc/

Disclaimer: I have never used it so I don't know how easy is to navigate
within.

If you're still in doubt about the format, I'll ask Nigel about the
structure and come with an answer next week.

**Comment by GuutBoy** [comment]
The reason many people have been using the Bristol Circuit format is because a number of circuits were published in that format, including classic benchmarks such as the AES circuit. So people who did not want to write the circuit them selves would use those. We have a parser for Bristol style circuits in FRESCO as well, and the documentation for it refers to https://www.cs.bris.ac.uk/Research/CryptographySecurity/MPC/ for details. But apparently, that site has been taken off-line. It would be interesting to know if that site has been moved? Meanwhile, it can be accessed here https://web.archive.org/web/20150501085203/https://www.cs.bris.ac.uk/Research/CryptographySecurity/MPC/

**Comment by dd23** [comment]
The website moved to with Nigel to Leuven: https://homes.esat.kuleuven.be/~nsmart/MPC/
